package edu.utdallas.sharedfiles.Challenge;

//
//This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
//See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
//Any modifications to this file will be lost upon recompilation of the source schema. 
//Generated on: 2014.04.25 at 07:45:04 PM CDT 
//


//package org.example.game;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
* <p>Java class for Summary complex type.
* 
* <p>The following schema fragment specifies the expected content contained within this class.
* 
* <pre>
* &lt;complexType name="Summary">
*   &lt;complexContent>
*     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
*       &lt;sequence>
*         &lt;element name="SummaryName" type="{http://www.w3.org/2001/XMLSchema}string"/>
*       &lt;/sequence>
*     &lt;/restriction>
*   &lt;/complexContent>
* &lt;/complexType>
* </pre>
* 
* 
*/
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Summary", propOrder = {
 "summaryName"
})
public class Summary {

 @XmlElement(name = "SummaryName", required = true)
 protected String summaryName;

 /**
  * Gets the value of the summaryName property.
  * 
  * @return
  *     possible object is
  *     {@link String }
  *     
  */
 public String getSummaryName() {
     return summaryName;
 }

 /**
  * Sets the value of the summaryName property.
  * 
  * @param value
  *     allowed object is
  *     {@link String }
  *     
  */
 public void setSummaryName(String value) {
     this.summaryName = value;
 }

}

/*
import java.util.List;

import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementWrapper;
import javax.xml.bind.annotation.XmlRootElement;

import edu.utdallas.sharedfiles.Shared.Asset;

@XmlRootElement(name = "Summary")
public class Summary 
{
	private String name;
    private List<Asset> assets;

	@XmlElement(name = "Name")
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}
	
	@Override
	public String toString()
	{
		return name;
	}

    @XmlElementWrapper(name = "Assets")
    @XmlElement(name = "AssetBase")
	public List<Asset> getAssets() {
		return assets;
	}

	public void setAssets(List<Asset> assets) {
		this.assets = assets;
	}
}
*/