//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
//Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2014.04.25 at 07:45:04 PM CDT
//


package edu.utdallas.gamespecification;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AnimationEffectType", propOrder = {
    "effect",
    "speed",
    "startLocation",
    "endLocation",
    "duration",
    "images"
})
public class AnimationEffectType {

    @XmlElement(name = "Effect", required = true)
    private List<String> effect;
    @XmlElement(name = "Speed", required = true)
    private SpeedType speed;
    @XmlElement(name = "StartLocation", required = true)
    private String startLocation;
    @XmlElement(name = "EndLocation", required = true)
    private String endLocation;
    @XmlElement(name = "Duration", required = true)
    private String duration;
    @XmlElement(name = "Images", required = true)
    private List<ItemImage> images;

    /**
     * Gets the value of the effect property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the
     * effect property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEffect().add(newItem);
     * </pre>
     *
     *
     * <p>
     * @return
     *      possible object is
     *      {@link String }
     *
     *
     */
    public final List<String> getEffect() {
        if (effect == null) {
            effect = new ArrayList<String>();
        }
        return this.effect;
    }

    /**
     * Gets the value of the speed property.
     *
     * @return
     *     possible object is
     *     {@link SpeedType }
     *
     */
    public final SpeedType getSpeed() {
        return speed;
    }

    /**
     * Sets the value of the speed property.
     *
     * @param value
     *     allowed object is
     *     {@link SpeedType }
     *
     */
    public final void setSpeed(final SpeedType value) {
        this.speed = value;
    }

    /**
     * Gets the value of the startLocation property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public final String getStartLocation() {
        return startLocation;
    }

    /**
     * Sets the value of the startLocation property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public final void setStartLocation(final String value) {
        this.startLocation = value;
    }

    /**
     * Gets the value of the endLocation property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public final String getEndLocation() {
        return endLocation;
    }

    /**
     * Sets the value of the endLocation property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public final void setEndLocation(final String value) {
        this.endLocation = value;
    }

    /**
     * Gets the value of the duration property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public final String getDuration() {
        return duration;
    }

    /**
     * Sets the value of the duration property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public final void setDuration(final String value) {
        this.duration = value;
    }

    /**
     * Gets the value of the images property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the
     * images property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getImages().add(newItem);
     * </pre>
     *
     *
     * <p>
     * @return
     *      possible object is
     *      {@link ItemImage }
     *
     *
     */
    public final List<ItemImage> getImages() {
        if (images == null) {
            images = new ArrayList<ItemImage>();
        }
        return this.images;
    }

}
