//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
//Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the
//source schema.
// Generated on: 2014.04.25 at 07:45:04 PM CDT
//

package edu.utdallas.gamespecification;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 *
 * @author Sean
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BackgroundType", propOrder = {
    "background"
})
public class BackgroundType {
/**
 * Background string represents the path to a background
 * asset.
 */
    @XmlElement(name = "Background", required = true)
    private String background;

    /**
     * Constructor, takes a string.
     * @param backgroundPath
     * expected object type:
     * {@link String}
     */
    public BackgroundType(final String backgroundPath) {
        this.background = backgroundPath;
    }

    /**
     * Default constructor, for when there are
     * no parameters yet.
     */
    public BackgroundType() {

    }
    /**
     * Gets the value of the background property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public final String getBackground() {
        return background;
    }

    /**
     * Sets the value of the background property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public final void setBackground(final String value) {
        this.background = value;
    }

}
