//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
//Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the
//source schema.
// Generated on: 2014.04.25 at 07:45:04 PM CDT
//


package edu.utdallas.gamespecification;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;

/**
 *
 * @author Sean
 * Defines the base class for Act, Scene, Screen, and
 * Challenge. Each of these has a transition and sequence.
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GameUnitType", propOrder = {
    "transition",
    "sequence"
})
@XmlSeeAlso({
    Act.class,
    Scene.class,
    Screen.class,
    Challenge.class
})
public class GameUnitType {

    /**
     * Holds a Transition object, which defines type and
     * duration of the transition.
     */
    @XmlElement(name = "Transition", required = true)
    private Transition transition;
    /**
     * Holds the sequence of the Game Unit, relative
     * to other items of the same type.
     */
    @XmlElement(name = "Sequence", required = true)
    private String sequence;

    /**
     * Gets the value of the transition property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public final Transition getTransition() {
        return transition;
    }

    /**
     * Sets the value of the transition property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public final void setTransition(final Transition value) {
        this.transition = value;
    }

    /**
     * Gets the value of the sequence property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public final String getSequence() {
        return sequence;
    }

    /**
     * Sets the value of the sequence property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public final void setSequence(final String value) {
        this.sequence = value;
    }

}
