//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2014.04.25 at 07:45:04 PM CDT
//


package edu.utdallas.gamespecification;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import edu.utdallas.sharedfiles.Shared.GameObject;


/**
 * <p>Java class for GenericInteraction complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="GenericInteraction">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.example.org/Game/}Prop">
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GenericInteraction", propOrder = {
		"text"
})
public class GenericInteraction
    extends Prop {
	
	@XmlElement(name = "Text", required = true)
    private String text;
	
		
	public GenericInteraction(GameObject rawObject) {
    	
    	super(rawObject);
    	this.text = rawObject.getText();    	
    }

	public GenericInteraction() {
		super();
		// TODO Auto-generated constructor stub
	}

	public GenericInteraction(String text) {
		super();
		this.text = text;
	}

	public String getText() {
		return text;
	}

	public void setText(String text) {
		this.text = text;
	}	

}
