package edu.utdallas.gamespecification;

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
//Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the
//source schema.
// Generated on: 2014.04.25 at 07:45:04 PM CDT
//


import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 *
 * @author Sean
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HintType", propOrder = {
    "hint"
})
public class Hint {

    /**
     * Represents the text displayed for the hint.
     */
    @XmlElement(name = "Hint")
    private String hint;

    /**
     * Default constructor, creates a
     * Hint with no text.
     */

    public Hint() {

    }
    /**
     *
     * @param hintText
     * Allowed type
     * {@link String}
     */
    public Hint(final String hintText) {
        this.hint = hintText;
    }

    /**
     * Gets the value of the hint property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public final String getHint() {
        return hint;
    }

    /**
     * Sets the value of the hint property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public final void setHint(final String value) {
        this.hint = value;
    }

}

