package edu.utdallas.sharedfiles.gamespec;

//
//This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
//See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
//Any modifications to this file will be lost upon recompilation of the source schema. 
//Generated on: 2014.04.25 at 07:45:04 PM CDT 
//


//package org.example.game;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
* <p>Java class for Item complex type.
* 
* <p>The following schema fragment specifies the expected content contained within this class.
* 
* <pre>
* &lt;complexType name="Item">
*   &lt;complexContent>
*     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
*       &lt;sequence>
*         &lt;element name="Itemname" type="{http://www.w3.org/2001/XMLSchema}string"/>
*       &lt;/sequence>
*     &lt;/restriction>
*   &lt;/complexContent>
* &lt;/complexType>
* </pre>
* 
* 
*/
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Item", propOrder = {
 "itemname"
})
@XmlSeeAlso({
 MultipleChoiceItem.class
})
public class Item {

 @XmlElement(name = "Itemname", required = true)
 protected String itemname;

 /**
  * Gets the value of the itemname property.
  * 
  * @return
  *     possible object is
  *     {@link String }
  *     
  */
 public String getItemname() {
     return itemname;
 }

 /**
  * Sets the value of the itemname property.
  * 
  * @param value
  *     allowed object is
  *     {@link String }
  *     
  */
 public void setItemname(String value) {
     this.itemname = value;
 }

}

/*
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSeeAlso;

@XmlRootElement(name = "Item")
@XmlSeeAlso({MultipleChoiceItem.class})
public class Item 
{
	private String name;
	private String learningObjective;

	@XmlElement(name = "Name")
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}
	
	@XmlElement(name = "Objective")
	public String getLearningObjective() {
		return learningObjective;
	}
	
	public void setLearningObjective(String learningObjective) {
		this.learningObjective = learningObjective;
	}
	
	@Override
	public String toString()
	{
		return name;
	}
}
*/