package edu.utdallas.sharedfiles.gamespec;

//
//This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
//See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
//Any modifications to this file will be lost upon recompilation of the source schema. 
//Generated on: 2014.04.25 at 07:45:04 PM CDT 
//


//package org.example.game;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
* <p>Java class for MultipleChoiceItem complex type.
* 
* <p>The following schema fragment specifies the expected content contained within this class.
* 
* <pre>
* &lt;complexType name="MultipleChoiceItem">
*   &lt;complexContent>
*     &lt;extension base="{http://www.example.org/Game/}Item">
*       &lt;sequence>
*         &lt;element name="Image" type="{http://www.example.org/Game/}ImageType"/>
*         &lt;element name="Stem" type="{http://www.example.org/Game/}StemType"/>
*         &lt;element name="Option" type="{http://www.example.org/Game/}OptionType"/>
*         &lt;element name="LearningObjective" type="{http://www.example.org/Game/}LearningObjectiveType"/>
*       &lt;/sequence>
*     &lt;/extension>
*   &lt;/complexContent>
* &lt;/complexType>
* </pre>
* 
* 
*/
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MultipleChoiceItem", propOrder = {
 "image",
 "stem",
 "option",
 "learningObjective"
})
public class MultipleChoiceItem
 extends Item
{

 @XmlElement(name = "Image", required = true)
 protected ItemImage image;
 @XmlElement(name = "Stem", required = true)
 protected Stem stem;
 @XmlElement(name = "Option", required = true)
 protected Option option;
 @XmlElement(name = "LearningObjective", required = true)
 protected LearningObjectiveType learningObjective;

 /**
  * Gets the value of the image property.
  * 
  * @return
  *     possible object is
  *     {@link ImageType }
  *     
  */
 public ItemImage getImage() {
     return image;
 }

 /**
  * Sets the value of the image property.
  * 
  * @param value
  *     allowed object is
  *     {@link ImageType }
  *     
  */
 public void setImage(ItemImage value) {
     this.image = value;
 }

 /**
  * Gets the value of the stem property.
  * 
  * @return
  *     possible object is
  *     {@link StemType }
  *     
  */
 public Stem getStem() {
     return stem;
 }

 /**
  * Sets the value of the stem property.
  * 
  * @param value
  *     allowed object is
  *     {@link StemType }
  *     
  */
 public void setStem(Stem value) {
     this.stem = value;
 }

 /**
  * Gets the value of the option property.
  * 
  * @return
  *     possible object is
  *     {@link OptionType }
  *     
  */
 public Option getOption() {
     return option;
 }

 /**
  * Sets the value of the option property.
  * 
  * @param value
  *     allowed object is
  *     {@link OptionType }
  *     
  */
 public void setOption(Option value) {
     this.option = value;
 }

 /**
  * Gets the value of the learningObjective property.
  * 
  * @return
  *     possible object is
  *     {@link LearningObjectiveType }
  *     
  */
 public LearningObjectiveType getLearningObjective() {
     return learningObjective;
 }

 /**
  * Sets the value of the learningObjective property.
  * 
  * @param value
  *     allowed object is
  *     {@link LearningObjectiveType }
  *     
  */
 public void setLearningObjective(LearningObjectiveType value) {
     this.learningObjective = value;
 }

}

/*
import java.util.List;

import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementWrapper;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

@XmlRootElement(name = "MultipleChoiceItem")
@XmlType(name = "MultipleChoiceItem")
public class MultipleChoiceItem extends Item
{
	private Stem stem;
	private ItemImage image;
	private List<Option> options;

    @XmlElement(name = "Stem")
	public Stem getStem() 
	{
		return stem;
	}
	public void setStem(Stem stem) 
	{
		this.stem = stem;
	}
    @XmlElement(name = "ItemImage")
	public ItemImage getImage() 
	{
		return image;
	}
	public void setImage(ItemImage image) 
	{
		this.image = image;
	}
	@XmlElementWrapper(name = "Options")
    @XmlElement(name = "Option")
	public List<Option> getOptions() 
	{
		return options;
	}
	public void setOptions(List<Option> options) 
	{
		this.options = options;
	}
}
*/