package edu.utdallas.sharedfiles.gamespec;

//
//This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
//See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
//Any modifications to this file will be lost upon recompilation of the source schema.
//Generated on: 2014.04.25 at 07:45:04 PM CDT
//


//package org.example.game;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
* <p>Java class for MultipleChoiceItem complex type.
*
* <p>The following schema fragment specifies the expected content contained within this class.
*
* <pre>
* &lt;complexType name="MultipleChoiceItem">
*   &lt;complexContent>
*     &lt;extension base="{http://www.example.org/Game/}Item">
*       &lt;sequence>
*         &lt;element name="Image" type="{http://www.example.org/Game/}ImageType"/>
*         &lt;element name="Stem" type="{http://www.example.org/Game/}StemType"/>
*         &lt;element name="Option" type="{http://www.example.org/Game/}OptionType"/>
*         &lt;element name="LearningObjective" type="{http://www.example.org/Game/}LearningObjectiveType"/>
*       &lt;/sequence>
*     &lt;/extension>
*   &lt;/complexContent>
* &lt;/complexType>
* </pre>
*
*
*/
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MultipleChoiceItem", propOrder = {
 "image",
 "stem",
 "option",
 "learningObjective"
})
public class MultipleChoiceItem
 extends Item
{

 @XmlElement(name = "Image", required = true)
 private ItemImage image;
 @XmlElement(name = "Stem", required = true)
 private Stem stem;
 @XmlElement(name = "Option", required = true)
 private Option option;
 @XmlElement(name = "LearningObjective", required = true)
 private LearningObjectiveType learningObjective;

 /**
  * Gets the value of the image property.
  *
  * @return
  *     possible object is
  *     {@link ImageType }
  *
  */
 public final ItemImage getImage() {
     return image;
 }

 /**
  * Sets the value of the image property.
  *
  * @param value
  *     allowed object is
  *     {@link ImageType }
  *
  */
 public final void setImage(final ItemImage value) {
     this.image = value;
 }

 /**
  * Gets the value of the stem property.
  *
  * @return
  *     possible object is
  *     {@link StemType }
  *
  */
 public final Stem getStem() {
     return stem;
 }

 /**
  * Sets the value of the stem property.
  *
  * @param value
  *     allowed object is
  *     {@link StemType }
  *
  */
 public final void setStem(final Stem value) {
     this.stem = value;
 }

 /**
  * Gets the value of the option property.
  *
  * @return
  *     possible object is
  *     {@link OptionType }
  *
  */
 public final Option getOption() {
     return option;
 }

 /**
  * Sets the value of the option property.
  *
  * @param value
  *     allowed object is
  *     {@link OptionType }
  *
  */
 public final void setOption(final Option value) {
     this.option = value;
 }

 /**
  * Gets the value of the learningObjective property.
  *
  * @return
  *     possible object is
  *     {@link LearningObjectiveType }
  *
  */
 public final LearningObjectiveType getLearningObjective() {
     return learningObjective;
 }

 /**
  * Sets the value of the learningObjective property.
  *
  * @param value
  *     allowed object is
  *     {@link LearningObjectiveType }
  *
  */
 public final void setLearningObjective(final LearningObjectiveType value) {
     this.learningObjective = value;
 }

}