/*package edu.utdallas.gamegenerator.Character;

import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

@XmlRootElement(name = "PlayerCharacter")
@XmlType(name = "PlayerCharacter")
public class PlayerCharacter extends Character
{

}
*/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2014.04.25 at 07:45:04 PM CDT
//


package edu.utdallas.sharedfiles.gamespec;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for Player complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="Player">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.example.org/Game/}Character">
 *       &lt;sequence>
 *         &lt;element name="PlayerID" type="{http://www.w3.org/2001/XMLSchema}ID"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Player", propOrder = {
    "playerID"
})
public class Player
    extends Character
{

    @XmlElement(name = "PlayerID", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String playerID;

    /**
     * Gets the value of the playerID property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getPlayerID() {
        return playerID;
    }

    /**
     * Sets the value of the playerID property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setPlayerID(String value) {
        this.playerID = value;
    }

}
