package edu.utdallas.sharedfiles.gamespec;

//
//This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
//See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
//Any modifications to this file will be lost upon recompilation of the source schema.
//Generated on: 2014.04.25 at 07:45:04 PM CDT
//


//package org.example.game;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
* <p>Java class for Summary complex type.
*
* <p>The following schema fragment specifies the expected content contained within this class.
*
* <pre>
* &lt;complexType name="Summary">
*   &lt;complexContent>
*     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
*       &lt;sequence>
*         &lt;element name="SummaryName" type="{http://www.w3.org/2001/XMLSchema}string"/>
*       &lt;/sequence>
*     &lt;/restriction>
*   &lt;/complexContent>
* &lt;/complexType>
* </pre>
*
*
*/
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Summary", propOrder = {
 "summaryName"
})
public class Summary {

 @XmlElement(name = "SummaryName", required = true)
 private String summaryName;

 /**
  * Gets the value of the summaryName property.
  *
  * @return
  *     possible object is
  *     {@link String }
  *
  */
 public final String getSummaryName() {
     return summaryName;
 }

 /**
  * Sets the value of the summaryName property.
  *
  * @param value
  *     allowed object is
  *     {@link String }
  *
  */
 public final void setSummaryName(final String value) {
     this.summaryName = value;
 }

}
