package edu.utdallas.sharedfiles.Structure;

//
//This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
//See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
//Any modifications to this file will be lost upon recompilation of the source schema. 
//Generated on: 2014.04.25 at 07:45:04 PM CDT 
//


//package org.example.game;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
* <p>Java class for SceneType complex type.
* 
* <p>The following schema fragment specifies the expected content contained within this class.
* 
* <pre>
* &lt;complexType name="SceneType">
*   &lt;complexContent>
*     &lt;extension base="{http://www.example.org/Game/}GameUnitType">
*       &lt;sequence>
*         &lt;element name="LearningObjective" type="{http://www.example.org/Game/}LearningObjectiveType"/>
*         &lt;element name="Screen" type="{http://www.example.org/Game/}ScreenType" maxOccurs="unbounded"/>
*         &lt;element name="Backgroud" type="{http://www.example.org/Game/}BackgroundType"/>
*         &lt;element name="Music" type="{http://www.example.org/Game/}MusicType" minOccurs="0"/>
*       &lt;/sequence>
*     &lt;/extension>
*   &lt;/complexContent>
* &lt;/complexType>
* </pre>
* 
* 
*/
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SceneType", propOrder = {
 "learningObjective",
 "screen",
 "backgroud",
 "music"
})
public class Scene//Type
 //extends GameUnitType
{

 @XmlElement(name = "LearningObjective", required = true)
 protected LearningObjectiveType learningObjective;
 @XmlElement(name = "Screen", required = true)
 protected List<Screen> screen;
 @XmlElement(name = "Backgroud", required = true)
 protected BackgroundType backgroud;
 @XmlElement(name = "Music")
 protected MusicType music;

 /**
  * Gets the value of the learningObjective property.
  * 
  * @return
  *     possible object is
  *     {@link LearningObjectiveType }
  *     
  */
 public LearningObjectiveType getLearningObjective() {
     return learningObjective;
 }

 /**
  * Sets the value of the learningObjective property.
  * 
  * @param value
  *     allowed object is
  *     {@link LearningObjectiveType }
  *     
  */
 public void setLearningObjective(LearningObjectiveType value) {
     this.learningObjective = value;
 }

 /**
  * Gets the value of the screen property.
  * 
  * <p>
  * This accessor method returns a reference to the live list,
  * not a snapshot. Therefore any modification you make to the
  * returned list will be present inside the JAXB object.
  * This is why there is not a <CODE>set</CODE> method for the screen property.
  * 
  * <p>
  * For example, to add a new item, do as follows:
  * <pre>
  *    getScreen().add(newItem);
  * </pre>
  * 
  * 
  * <p>
  * Objects of the following type(s) are allowed in the list
  * {@link ScreenType }
  * 
  * 
  */
 public List<Screen> getScreen() {
     if (screen == null) {
         screen = new ArrayList<Screen>();
     }
     return this.screen;
 }

 /**
  * Gets the value of the backgroud property.
  * 
  * @return
  *     possible object is
  *     {@link BackgroundType }
  *     
  */
 public BackgroundType getBackgroud() {
     return backgroud;
 }

 /**
  * Sets the value of the backgroud property.
  * 
  * @param value
  *     allowed object is
  *     {@link BackgroundType }
  *     
  */
 public void setBackgroud(BackgroundType value) {
     this.background = value;
 }

 /**
  * Gets the value of the music property.
  * 
  * @return
  *     possible object is
  *     {@link MusicType }
  *     
  */
 public MusicType getMusic() {
     return music;
 }

 /**
  * Sets the value of the music property.
  * 
  * @param value
  *     allowed object is
  *     {@link MusicType }
  *     
  */
 public void setMusic(MusicType value) {
     this.music = value;
 }

}

/*
import edu.utdallas.sharedfiles.Shared.Asset;
import edu.utdallas.sharedfiles.Shared.Behavior;

import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementWrapper;
import javax.xml.bind.annotation.XmlRootElement;

import java.util.List;
import java.util.UUID;

/**
 * User: clocke
 * Date: 2/24/13
 * Time: 8:58 PM
 *//*
@XmlRootElement(name = "Scene")
public class Scene {
    List<Screen> screens;
    String background;
    String name;
    String backgroundAudio;
    UUID id = UUID.randomUUID();
    List<Behavior> behaviorList;
    List<Asset> assets;
    List<String> learningObjectives;

    public List<Screen> getScreens() {
        return screens;
    }

    @XmlElementWrapper(name = "Screens")
    @XmlElement(name = "Screen")
    public void setScreens(List<Screen> screens) {
        this.screens = screens;
    }

    @XmlElement(name = "Background")
    public String getBackground() {
        return background;
    }

    public void setBackground(String background) {
        this.background = background;
    }

    @XmlElement(name = "Name")
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @XmlElement(name = "ID")
    public UUID getId() {
        return id;
    }

    public void setId(UUID id) {
        this.id = id;
    }
    
    @XmlElement(name = "BackgroundAudio")
    public String getBackgroundMusic() {
        return backgroundAudio;
    }
    
    public void setBackgroundMusic(String backgroundMusic) {
    	this.backgroundAudio=backgroundMusic;
    }

    @XmlElement
    public List<Behavior> getBehaviorList() {
        return behaviorList;
    }

    public void setBehaviorList(List<Behavior> behaviorList) {
        this.behaviorList = behaviorList;
    }

    @XmlElementWrapper(name = "Assets")
    @XmlElement(name = "Asset")
    public List<Asset> getAssets() {
        return assets;
    }

    public void setAssets(List<Asset> assets) {
        this.assets = assets;
    }
    
    
    @XmlElementWrapper(name = "LearningObjectives")
    @XmlElement(name = "Objective")
    public List<String> getLearningObjectives() {
        return learningObjectives;
    }

    public void setLearningObjectives(List<String> lOs) {
        this.learningObjectives = lOs;
    }
    
    @Override
    public String toString()
    {
    	return name;
    }
}
*/