package edu.utdallas.gamePlayEngine.model.gamespec;

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2014.04.25 at 07:45:04 PM CDT
//


//package org.example.game;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OptionType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="OptionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Assessment" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Reward" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Feedback" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Hint" type="{http://www.example.org/Game/}HintType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OptionType", propOrder = {
    "assessment",
    "reward",
    "feedback",
    "hint"
})
public class Option {

    @XmlElement(name = "Assessment", required = true)
    private String assessment;
    @XmlElement(name = "Reward", required = true)
    private String reward;
    @XmlElement(name = "Feedback", required = true)
    private String feedback;
    @XmlElement(name = "Hint")
    private Hint hint;

    /**
     * Gets the value of the assessment property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public final String getAssessment() {
        return assessment;
    }

    /**
     * Sets the value of the assessment property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public final void setAssessment(final String value) {
        this.assessment = value;
    }

    /**
     * Gets the value of the reward property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public final String getReward() {
        return reward;
    }

    /**
     * Sets the value of the reward property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public final void setReward(final String value) {
        this.reward = value;
    }

    /**
     * Gets the value of the feedback property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public final String getFeedback() {
        return feedback;
    }

    /**
     * Sets the value of the feedback property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public final void setFeedback(final String value) {
        this.feedback = value;
    }

    /**
     * Gets the value of the hint property.
     *
     * @return
     *     possible object is
     *     {@link HintType }
     *
     */
    public final Hint getHint() {
        return hint;
    }

    /**
     * Sets the value of the hint property.
     *
     * @param value
     *     allowed object is
     *     {@link HintType }
     *
     */
    public final void setHint(final Hint value) {
        this.hint = value;
    }

}
